// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by: tools/gen_denylist.mjs
// Generated at: 2026-02-18T18:33:24.742Z
//
// This module contains a conservative domain denylist compiled from filter lists.
// We extract ONLY a small subset of rules (||domain^).
//
// Sources:
 * - blp_porn_noip: https://raw.githubusercontent.com/blocklistproject/Lists/b9b24117611a318f80a359caec454604f707dc57/porn.txt
 * - blp_gambling_noip: https://raw.githubusercontent.com/blocklistproject/Lists/b9b24117611a318f80a359caec454604f707dc57/gambling.txt
//
// Domain count: 0

export const DENY_DOMAINS: ReadonlySet<string> = new Set<string>([

]);
